export const refs = {
  mainLibrary: document.querySelector('.js-main-library'),
  myLibrary: document.querySelector('.js-my-library'),
  authBtnWrap: document.querySelector('.auth-link-wrap'),
  form: document.querySelector('#search-form'),
  serchError: document.querySelector('.is-hidden'),
  scrollToTopBtn: document.querySelector('#scrollToTopBtn'),
  rootElement: document.documentElement,
  window,
  inputEl: document.querySelector('#slider'),
  main: document.querySelector('main'),
  paginationContainer: document.querySelector('#paginationhomepage'),
  lybraryGallery: document.querySelector('.library-gallery'),
  lybraryQueueBtn: document.querySelector('.queue'),
  lybraryWatchedBtn: document.querySelector('.watched'),
  lybraryBtnsWrap: document.querySelector('.library-btns'),
  lybraryError: document.querySelector('.library-error-wrap'),
  trendsBtns: document.querySelectorAll('.genre-button'),
  loadOptions: {
    clickToClose: true,
    svgSize: '100px',
    svgColor: '#FF6B01',
  },
  mesageOption: {
    showOnlyTheLastOne: true,
    clickToClose: true,
  },
};
